#ifndef BENCHMARKSETTINGS_H
#define BENCHMARKSETTINGS_H

#define BENCHMARK_MIN_TIME 10.0
#define BENCHMARK_MAX_TIME 60.0

#define BENCHMARK_MIN_ITER 10

#define BENCHMARK_MEAN_PRECISION 100.0
#define BENCHMARK_CONVERGENCE_RATIO 0.9

#endif // BENCHMARKSETTINGS_H
